### ISSUE TITLE
toString() method in RDN class escapes special characters and Umlauts

### ISSUE THREAD

**Issue by anessi** [ldapjs/dn#3] opened 2024-03-11 09:26 UTC
During LDAP integration of our backstage.io project I noticed that authentication of users which have Umlaut (e.g. äöü) in their DN fails. This is due to the fact that any Umlaut in the [RDN gets escaped](https://github.com/ldapjs/dn/blob/master/lib/rdn.js#L177).

The `toString()` function is called in https://github.com/ldapjs/dn/blob/master/lib/dn.js#L253.

In https://github.com/ldapjs/dn/commit/57f54c7973cdc8a2abfea1354b002f19e3ba9224 I noticed that a feature has been implemented to suppress encoding the values, but there's not way to configure this.
Setting options globally seems to be deprecated and no longer supported

The only workaround I have found is to monkey patch the `toString()` function like this:

```
import { RDN } from 'ldapjs'
let originalToString = RDN.prototype.toString;
RDN.prototype.toString = function() {
  // @ts-ignore
  return originalToString.apply(this, [{ unescaped: true }])
};
```

Is there a better way to configure this or are there any plans to make it configurable?
Disclaimer: I'm a not a JS dev 😃

**Comment by jsumners** [comment] 2024-03-11 12:30
This is a duplicate of https://github.com/ldapjs/filter/pull/9#discussion_r1401459812

**Closed as not planned by jsumners** 2024-03-11 12:30 UTC
